name: action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build_Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up GTest path
      run: |
        export GTEST_LIBRARY=/usr/lib/libgtest.a  # or the path to your GTest library
        export GTEST_INCLUDE_DIR=/usr/include/gtest  # or the path to your GTest include directory

    - name: Configure example
      run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build example
      run: cmake --build ${{github.workspace}}/build
