name: action
on:
  push:
    branches:
      - main
jobs:
  prototype_cont:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: List files in workspace
      run: ls -R ${{github.workspace}}

    - name: Create .build directory
      run: mkdir -p ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run programm.cpp
      run: ${{github.workspace}}/build/DecoratorPattern

    - name: Run tests
      run: ${{github.workspace}}/build/tests
