name: action
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      uses: ilammy/setup-cpp-cmake@v2
      with:
        cmake-version: '3.21'
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build --config Release
    - name: Run Tests
      run: ./build/tests

